contact_links:
  - name: Are you looking for documentation on daschcon2025-omeka2dsp?
    url: https://maehr.github.io/daschcon2025-omeka2dsp
    about: Please see the documentation for daschcon2025-omeka2dsp on its GitHub Pages page.
  - name: Do you want to discuss daschcon2025-omeka2dsp with the community?
    url: https://github.com/maehr/daschcon2025-omeka2dsp/discussions
    about: Please see the discussions page for daschcon2025-omeka2dsp.
blank_issues_enabled: true
